# pytype: skip-file
# pylint: disable=protected-access
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: localharness.proto
# Protobuf Python Version: 0.20260430.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    0,
    20260430,
    0,
    '',
    'localharness.proto',
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12localharness.proto\x12\x18\x61ntigravity.localharness"(\n\x0bInputConfig\x12\x19\n\x11storage_directory\x18\x01'
    b' \x01(\t"V\n\x1bInitializeConversationEvent\x12\x37\n\x06\x63onfig\x18\x01'
    b' \x01(\x0b\x32\'.antigravity.localharness.HarnessConfig"\xe2\x03\n\rHarnessConfig\x12\x12\n\ncascade_id\x18\x01'
    b' \x01(\t\x12?\n\rgemini_config\x18\x02'
    b' \x01(\x0b\x32&.antigravity.localharness.GeminiConfigH\x00\x12=\n\x0cgemma_config\x18\x03'
    b' \x01(\x0b\x32%.antigravity.localharness.GemmaConfigH\x00\x12I\n\x13system_instructions\x18\x04'
    b' \x01(\x0b\x32,.antigravity.localharness.SystemInstructions\x12-\n\x05tools\x18\x05'
    b' \x03(\x0b\x32\x1e.antigravity.localharness.Tool\x12\x46\n\x12harness_side_tools\x18\x06'
    b' \x01(\x0b\x32*.antigravity.localharness.HarnessSideTools\x12\x1c\n\x14\x63ompaction_threshold\x18\x07'
    b' \x01(\r\x12\x37\n\nworkspaces\x18\x08'
    b' \x03(\x0b\x32#.antigravity.localharness.Workspace\x12\x14\n\x0cskills_paths\x18\t'
    b' \x03(\tB\x0e\n\x0cmodel_config"l\n\tWorkspace\x12M\n\x14\x66ilesystem_workspace\x18\x01'
    b' \x01(\x0b\x32-.antigravity.localharness.FilesystemWorkspaceH\x00\x42\x10\n\x0eworkspace_type"(\n\x13\x46ilesystemWorkspace\x12\x11\n\tdirectory\x18\x01'
    b' \x01(\t"\xaf\x01\n\x0cGeminiConfig\x12\x0f\n\x07\x61pi_key\x18\x01'
    b' \x01(\t\x12\x10\n\x08\x62\x61se_url\x18\x02'
    b' \x01(\t\x12*\n\nmodel_name\x18\x03'
    b' \x01(\t:\x16gemini-3-flash-preview\x12\x16\n\x0ethinking_level\x18\x04'
    b' \x01(\t\x12\x1a\n\x12\x65nable_url_context\x18\x05'
    b' \x01(\x08\x12\x1c\n\x14\x65nable_google_search\x18\x06'
    b' \x01(\x08"3\n\x0bGemmaConfig\x12\x10\n\x08\x62\x61se_url\x18\x01'
    b' \x01(\t\x12\x12\n\nmodel_name\x18\x02'
    b' \x01(\t"\xac\x01\n\x12SystemInstructions\x12\x44\n\x06\x63ustom\x18\x01'
    b' \x01(\x0b\x32\x32.antigravity.localharness.CustomSystemInstructionsH\x00\x12H\n\x08\x61ppended\x18\x02'
    b' \x01(\x0b\x32\x34.antigravity.localharness.AppendedSystemInstructionsH\x00\x42\x06\n\x04type"\x81\x01\n\x18\x43ustomSystemInstructions\x12\x45\n\x04part\x18\x01'
    b' \x03(\x0b\x32\x37.antigravity.localharness.CustomSystemInstructions.Part\x1a\x1e\n\x04Part\x12\x0e\n\x04text\x18\x01'
    b' \x01(\tH\x00\x42\x06\n\x04part"\xb9\x01\n\x1a\x41ppendedSystemInstructions\x12\x17\n\x0f\x63ustom_identity\x18\x01'
    b' \x01(\t\x12W\n\x11\x61ppended_sections\x18\x02'
    b' \x03(\x0b\x32<.antigravity.localharness.AppendedSystemInstructions.Section\x1a)\n\x07Section\x12\r\n\x05title\x18\x01'
    b' \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02'
    b' \x01(\t"g\n\x04Tool\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02'
    b' \x01(\t\x12\x1e\n\x16parameters_json_schema\x18\x03'
    b' \x01(\t\x12\x1c\n\x14response_json_schema\x18\x04'
    b' \x01(\t"\xa4\x05\n\x10HarnessSideTools\x12\x36\n\x04\x66ind\x18\x01'
    b' \x01(\x0b\x32(.antigravity.localharness.FindToolConfig\x12\x43\n\x0brun_command\x18\x02'
    b' \x01(\x0b\x32..antigravity.localharness.RunCommandToolConfig\x12<\n\tsubagents\x18\x03'
    b' \x01(\x0b\x32).antigravity.localharness.SubagentsConfig\x12\x45\n\x0euser_questions\x18\x04'
    b' \x01(\x0b\x32-.antigravity.localharness.UserQuestionsConfig\x12?\n\tfile_edit\x18\x05'
    b' \x01(\x0b\x32,.antigravity.localharness.FileEditToolConfig\x12?\n\tview_file\x18\x06'
    b' \x01(\x0b\x32,.antigravity.localharness.ViewFileToolConfig\x12\x46\n\rwrite_to_file\x18\x07'
    b' \x01(\x0b\x32/.antigravity.localharness.WriteToFileToolConfig\x12\x43\n\x0bgrep_search\x18\x08'
    b' \x01(\x0b\x32..antigravity.localharness.GrepSearchToolConfig\x12=\n\x08list_dir\x18\t'
    b' \x01(\x0b\x32+.antigravity.localharness.ListDirToolConfig\x12@\n\x0bpermissions\x18\n'
    b' \x01(\x0b\x32+.antigravity.localharness.PermissionsConfig"\'\n\x0e\x46indToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"-\n\x14RunCommandToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"(\n\x0fSubagentsConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true",\n\x13UserQuestionsConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"+\n\x12\x46ileEditToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"+\n\x12ViewFileToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true".\n\x15WriteToFileToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"-\n\x14GrepSearchToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"*\n\x11ListDirToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"9\n\x11PermissionsConfig\x12$\n\x1c\x65nforce_workspace_validation\x18\x01'
    b' \x01(\x08"-\n\x0cOutputConfig\x12\x0c\n\x04port\x18\x01'
    b' \x01(\x05\x12\x0f\n\x07\x61pi_key\x18\x02'
    b' \x01(\t"\x8b\x02\n\x0bOutputEvent\x12\x0f\n\x07seq_num\x18\x01'
    b' \x01(\x03\x12\x18\n\x10timestamp_micros\x18\x02'
    b' \x01(\x03\x12;\n\x0bstep_update\x18\n'
    b' \x01(\x0b\x32$.antigravity.localharness.StepUpdateH\x00\x12R\n\x17trajectory_state_update\x18\x0b'
    b' \x01(\x0b\x32/.antigravity.localharness.TrajectoryStateUpdateH\x00\x12\x37\n\ttool_call\x18\x0c'
    b' \x01(\x0b\x32".antigravity.localharness.ToolCallH\x00\x42\x07\n\x05\x65vent"\xd4\n\n\nStepUpdate\x12\x12\n\ncascade_id\x18\x01'
    b' \x01(\t\x12\x15\n\rtrajectory_id\x18\x02'
    b' \x01(\t\x12\x12\n\nstep_index\x18\x03 \x01(\r\x12\x39\n\x05state\x18\x04'
    b' \x01(\x0e\x32*.antigravity.localharness.StepUpdate.State\x12;\n\x06source\x18\x05'
    b' \x01(\x0e\x32+.antigravity.localharness.StepUpdate.Source\x12;\n\x06target\x18\x06'
    b' \x01(\x0e\x32+.antigravity.localharness.StepUpdate.Target\x12\x15\n\rerror_message\x18\x07'
    b' \x01(\t\x12\x0c\n\x04text\x18\x14'
    b' \x01(\t\x12\x45\n\x0elist_directory\x18\x15'
    b' \x01(\x0b\x32-.antigravity.localharness.ActionListDirectory\x12;\n\tfind_file\x18\x16'
    b' \x01(\x0b\x32(.antigravity.localharness.ActionFindFile\x12I\n\x10search_directory\x18\x17'
    b' \x01(\x0b\x32/.antigravity.localharness.ActionSearchDirectory\x12;\n\tview_file\x18\x18'
    b' \x01(\x0b\x32(.antigravity.localharness.ActionViewFile\x12?\n\x0b\x63reate_file\x18\x19'
    b' \x01(\x0b\x32*.antigravity.localharness.ActionCreateFile\x12;\n\tedit_file\x18\x1a'
    b' \x01(\x0b\x32(.antigravity.localharness.ActionEditFile\x12?\n\x0brun_command\x18\x1b'
    b' \x01(\x0b\x32*.antigravity.localharness.ActionRunCommand\x12>\n\ncompaction\x18\x1c'
    b' \x01(\x0b\x32*.antigravity.localharness.ActionCompaction\x12G\n\x0finvoke_subagent\x18\x1d'
    b' \x01(\x0b\x32..antigravity.localharness.ActionInvokeSubagent\x12\x14\n\x0crequest_text\x18\x32'
    b' \x01(\t\x12T\n\x19tool_confirmation_request\x18\x33'
    b' \x01(\x0b\x32\x31.antigravity.localharness.ToolConfirmationRequest\x12I\n\x11questions_request\x18\x34'
    b' \x01(\x0b\x32..antigravity.localharness.UserQuestionsRequest"m\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x10\n\x0cSTATE_ACTIVE\x10\x01\x12\x0e\n\nSTATE_DONE\x10\x02\x12\x1a\n\x16STATE_WAITING_FOR_USER\x10\x03\x12\x0f\n\x0bSTATE_ERROR\x10\x04"V\n\x06Source\x12\x16\n\x12SOURCE_UNSPECIFIED\x10\x00\x12\x11\n\rSOURCE_SYSTEM\x10\x01\x12\x0f\n\x0bSOURCE_USER\x10\x02\x12\x10\n\x0cSOURCE_MODEL\x10\x03"[\n\x06Target\x12\x16\n\x12TARGET_UNSPECIFIED\x10\x00\x12\x0f\n\x0bTARGET_USER\x10\x01\x12\x10\n\x0cTARGET_MODEL\x10\x02\x12\x16\n\x12TARGET_ENVIRONMENT\x10\x03"-\n\x13\x41\x63tionListDirectory\x12\x16\n\x0e\x64irectory_path\x18\x01'
    b' \x01(\t"7\n\x0e\x41\x63tionFindFile\x12\x16\n\x0e\x64irectory_path\x18\x01'
    b' \x01(\t\x12\r\n\x05query\x18\x02'
    b' \x01(\t">\n\x15\x41\x63tionSearchDirectory\x12\x16\n\x0e\x64irectory_path\x18\x01'
    b' \x01(\t\x12\r\n\x05query\x18\x02'
    b' \x01(\t"I\n\x0e\x41\x63tionViewFile\x12\x11\n\tfile_path\x18\x01'
    b' \x01(\t\x12\x12\n\nstart_line\x18\x02'
    b' \x01(\r\x12\x10\n\x08\x65nd_line\x18\x03'
    b' \x01(\r"7\n\x10\x41\x63tionCreateFile\x12\x11\n\tfile_path\x18\x01'
    b' \x01(\t\x12\x10\n\x08\x63ontents\x18\x02'
    b' \x01(\t"\xba\x03\n\x0e\x41\x63tionEditFile\x12\x11\n\tfile_path\x18\x01'
    b' \x01(\t\x12\x46\n\ndiff_block\x18\x02'
    b' \x03(\x0b\x32\x32.antigravity.localharness.ActionEditFile.DiffBlock\x1a\xd7\x01\n\x08\x44iffLine\x12\x0c\n\x04text\x18\x01'
    b' \x01(\t\x12L\n\x06\x61\x63tion\x18\x02'
    b' \x01(\x0e\x32<.antigravity.localharness.ActionEditFile.DiffLine.LineAction"o\n\nLineAction\x12\x1b\n\x17LINE_ACTION_UNSPECIFIED\x10\x00\x12\x16\n\x12LINE_ACTION_INSERT\x10\x01\x12\x16\n\x12LINE_ACTION_DELETE\x10\x02\x12\x14\n\x10LINE_ACTION_NONE\x10\x03\x1as\n\tDiffBlock\x12\x12\n\nstart_line\x18\x01'
    b' \x01(\x05\x12\x10\n\x08\x65nd_line\x18\x02'
    b' \x01(\x05\x12@\n\x05lines\x18\x03'
    b' \x03(\x0b\x32\x31.antigravity.localharness.ActionEditFile.DiffLine"=\n\x10\x41\x63tionRunCommand\x12\x14\n\x0c\x63ommand_line\x18\x01'
    b' \x01(\t\x12\x13\n\x0bworking_dir\x18\x02'
    b' \x01(\t"\x12\n\x10\x41\x63tionCompaction"\x16\n\x14\x41\x63tionInvokeSubagent"\x19\n\x17ToolConfirmationRequest"Q\n\x14UserQuestionsRequest\x12\x39\n\tquestions\x18\x01'
    b' \x03(\x0b\x32&.antigravity.localharness.UserQuestion"d\n\x0cUserQuestion\x12\x43\n\x0fmultiple_choice\x18\x01'
    b' \x01(\x0b\x32(.antigravity.localharness.MultipleChoiceH\x00\x42\x0f\n\rquestion_type"L\n\x0eMultipleChoice\x12\x10\n\x08question\x18\x01'
    b' \x01(\t\x12\x0f\n\x07\x63hoices\x18\x02'
    b' \x03(\t\x12\x17\n\x0fis_multi_select\x18\x03'
    b' \x01(\x08"\xfb\x02\n\nInputEvent\x12\x14\n\nuser_input\x18\x01'
    b' \x01(\tH\x00\x12\x41\n\x12\x63omplex_user_input\x18\x07'
    b' \x01(\x0b\x32#.antigravity.localharness.UserInputH\x00\x12G\n\x11tool_confirmation\x18\x02'
    b' \x01(\x0b\x32*.antigravity.localharness.ToolConfirmationH\x00\x12?\n\rtool_response\x18\x03'
    b' \x01(\x0b\x32&.antigravity.localharness.ToolResponseH\x00\x12L\n\x11question_response\x18\x04'
    b' \x01(\x0b\x32/.antigravity.localharness.UserQuestionsResponseH\x00\x12\x16\n\x0chalt_request\x18\x05'
    b' \x01(\x08H\x00\x12\x1b\n\x11\x61utomated_trigger\x18\x06'
    b' \x01(\tH\x00\x42\x07\n\x05\x65vent"\xdf\x01\n\tUserInput\x12\x37\n\x05parts\x18\x01'
    b' \x03(\x0b\x32(.antigravity.localharness.UserInput.Part\x1a=\n\x05Media\x12\x11\n\tmime_type\x18\x01'
    b' \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02'
    b' \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03'
    b' \x01(\x0c\x1aZ\n\x04Part\x12\x0e\n\x04text\x18\x01'
    b' \x01(\tH\x00\x12:\n\x05media\x18\x02'
    b' \x01(\x0b\x32).antigravity.localharness.UserInput.MediaH\x00\x42\x06\n\x04part"O\n\x10ToolConfirmation\x12\x15\n\rtrajectory_id\x18\x01'
    b' \x01(\t\x12\x12\n\nstep_index\x18\x02'
    b' \x01(\r\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x03'
    b' \x01(\x08"\xb7\x01\n\x15TrajectoryStateUpdate\x12\x15\n\rtrajectory_id\x18\x02'
    b' \x01(\t\x12\x44\n\x05state\x18\x03'
    b' \x01(\x0e\x32\x35.antigravity.localharness.TrajectoryStateUpdate.State"A\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n\rSTATE_RUNNING\x10\x01\x12\x0e\n\nSTATE_IDLE\x10\x02"<\n\x08ToolCall\x12\n\n\x02id\x18\x01'
    b' \x01(\t\x12\x0c\n\x04name\x18\x02'
    b' \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x03'
    b' \x01(\t"n\n\x0cToolResponse\x12\n\n\x02id\x18\x01'
    b' \x01(\t\x12\x15\n\rresponse_json\x18\x02'
    b' \x01(\t\x12;\n\x12supplemental_media\x18\x03'
    b' \x03(\x0b\x32\x1f.antigravity.localharness.Media"\x8c\x02\n\x15UserQuestionsResponse\x12\x15\n\rtrajectory_id\x18\x01'
    b' \x01(\t\x12\x12\n\nstep_index\x18\x02'
    b' \x01(\r\x12\x13\n\tcancelled\x18\x03'
    b' \x01(\x08H\x00\x12U\n\x08response\x18\x04'
    b' \x01(\x0b\x32\x41.antigravity.localharness.UserQuestionsResponse.QuestionsResponseH\x00\x1aR\n\x11QuestionsResponse\x12=\n\x07\x61nswers\x18\x01'
    b' \x03(\x0b\x32,.antigravity.localharness.UserQuestionAnswerB\x08\n\x06result"\x86\x01\n\x12UserQuestionAnswer\x12\x14\n\nunanswered\x18\x01'
    b' \x01(\x08H\x00\x12P\n\x16multiple_choice_answer\x18\x02'
    b' \x01(\x0b\x32..antigravity.localharness.MultipleChoiceAnswerH\x00\x42\x08\n\x06\x61nswer"R\n\x14MultipleChoiceAnswer\x12\x1f\n\x17selected_choice_indices\x18\x01'
    b' \x03(\x05\x12\x19\n\x11\x66reeform_response\x18\x02'
    b' \x01(\t"=\n\x05Media\x12\x11\n\tmime_type\x18\x01'
    b' \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02'
    b' \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03'
    b' \x01(\x0c\x62\x08\x65\x64itionsp\xe9\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'localharness_pb2', _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUTCONFIG']._serialized_start = 48
  _globals['_INPUTCONFIG']._serialized_end = 88
  _globals['_INITIALIZECONVERSATIONEVENT']._serialized_start = 90
  _globals['_INITIALIZECONVERSATIONEVENT']._serialized_end = 176
  _globals['_HARNESSCONFIG']._serialized_start = 179
  _globals['_HARNESSCONFIG']._serialized_end = 661
  _globals['_WORKSPACE']._serialized_start = 663
  _globals['_WORKSPACE']._serialized_end = 771
  _globals['_FILESYSTEMWORKSPACE']._serialized_start = 773
  _globals['_FILESYSTEMWORKSPACE']._serialized_end = 813
  _globals['_GEMINICONFIG']._serialized_start = 816
  _globals['_GEMINICONFIG']._serialized_end = 991
  _globals['_GEMMACONFIG']._serialized_start = 993
  _globals['_GEMMACONFIG']._serialized_end = 1044
  _globals['_SYSTEMINSTRUCTIONS']._serialized_start = 1047
  _globals['_SYSTEMINSTRUCTIONS']._serialized_end = 1219
  _globals['_CUSTOMSYSTEMINSTRUCTIONS']._serialized_start = 1222
  _globals['_CUSTOMSYSTEMINSTRUCTIONS']._serialized_end = 1351
  _globals['_CUSTOMSYSTEMINSTRUCTIONS_PART']._serialized_start = 1321
  _globals['_CUSTOMSYSTEMINSTRUCTIONS_PART']._serialized_end = 1351
  _globals['_APPENDEDSYSTEMINSTRUCTIONS']._serialized_start = 1354
  _globals['_APPENDEDSYSTEMINSTRUCTIONS']._serialized_end = 1539
  _globals['_APPENDEDSYSTEMINSTRUCTIONS_SECTION']._serialized_start = 1498
  _globals['_APPENDEDSYSTEMINSTRUCTIONS_SECTION']._serialized_end = 1539
  _globals['_TOOL']._serialized_start = 1541
  _globals['_TOOL']._serialized_end = 1644
  _globals['_HARNESSSIDETOOLS']._serialized_start = 1647
  _globals['_HARNESSSIDETOOLS']._serialized_end = 2323
  _globals['_FINDTOOLCONFIG']._serialized_start = 2325
  _globals['_FINDTOOLCONFIG']._serialized_end = 2364
  _globals['_RUNCOMMANDTOOLCONFIG']._serialized_start = 2366
  _globals['_RUNCOMMANDTOOLCONFIG']._serialized_end = 2411
  _globals['_SUBAGENTSCONFIG']._serialized_start = 2413
  _globals['_SUBAGENTSCONFIG']._serialized_end = 2453
  _globals['_USERQUESTIONSCONFIG']._serialized_start = 2455
  _globals['_USERQUESTIONSCONFIG']._serialized_end = 2499
  _globals['_FILEEDITTOOLCONFIG']._serialized_start = 2501
  _globals['_FILEEDITTOOLCONFIG']._serialized_end = 2544
  _globals['_VIEWFILETOOLCONFIG']._serialized_start = 2546
  _globals['_VIEWFILETOOLCONFIG']._serialized_end = 2589
  _globals['_WRITETOFILETOOLCONFIG']._serialized_start = 2591
  _globals['_WRITETOFILETOOLCONFIG']._serialized_end = 2637
  _globals['_GREPSEARCHTOOLCONFIG']._serialized_start = 2639
  _globals['_GREPSEARCHTOOLCONFIG']._serialized_end = 2684
  _globals['_LISTDIRTOOLCONFIG']._serialized_start = 2686
  _globals['_LISTDIRTOOLCONFIG']._serialized_end = 2728
  _globals['_PERMISSIONSCONFIG']._serialized_start = 2730
  _globals['_PERMISSIONSCONFIG']._serialized_end = 2787
  _globals['_OUTPUTCONFIG']._serialized_start = 2789
  _globals['_OUTPUTCONFIG']._serialized_end = 2834
  _globals['_OUTPUTEVENT']._serialized_start = 2837
  _globals['_OUTPUTEVENT']._serialized_end = 3104
  _globals['_STEPUPDATE']._serialized_start = 3107
  _globals['_STEPUPDATE']._serialized_end = 4471
  _globals['_STEPUPDATE_STATE']._serialized_start = 4181
  _globals['_STEPUPDATE_STATE']._serialized_end = 4290
  _globals['_STEPUPDATE_SOURCE']._serialized_start = 4292
  _globals['_STEPUPDATE_SOURCE']._serialized_end = 4378
  _globals['_STEPUPDATE_TARGET']._serialized_start = 4380
  _globals['_STEPUPDATE_TARGET']._serialized_end = 4471
  _globals['_ACTIONLISTDIRECTORY']._serialized_start = 4473
  _globals['_ACTIONLISTDIRECTORY']._serialized_end = 4518
  _globals['_ACTIONFINDFILE']._serialized_start = 4520
  _globals['_ACTIONFINDFILE']._serialized_end = 4575
  _globals['_ACTIONSEARCHDIRECTORY']._serialized_start = 4577
  _globals['_ACTIONSEARCHDIRECTORY']._serialized_end = 4639
  _globals['_ACTIONVIEWFILE']._serialized_start = 4641
  _globals['_ACTIONVIEWFILE']._serialized_end = 4714
  _globals['_ACTIONCREATEFILE']._serialized_start = 4716
  _globals['_ACTIONCREATEFILE']._serialized_end = 4771
  _globals['_ACTIONEDITFILE']._serialized_start = 4774
  _globals['_ACTIONEDITFILE']._serialized_end = 5216
  _globals['_ACTIONEDITFILE_DIFFLINE']._serialized_start = 4884
  _globals['_ACTIONEDITFILE_DIFFLINE']._serialized_end = 5099
  _globals['_ACTIONEDITFILE_DIFFLINE_LINEACTION']._serialized_start = 4988
  _globals['_ACTIONEDITFILE_DIFFLINE_LINEACTION']._serialized_end = 5099
  _globals['_ACTIONEDITFILE_DIFFBLOCK']._serialized_start = 5101
  _globals['_ACTIONEDITFILE_DIFFBLOCK']._serialized_end = 5216
  _globals['_ACTIONRUNCOMMAND']._serialized_start = 5218
  _globals['_ACTIONRUNCOMMAND']._serialized_end = 5279
  _globals['_ACTIONCOMPACTION']._serialized_start = 5281
  _globals['_ACTIONCOMPACTION']._serialized_end = 5299
  _globals['_ACTIONINVOKESUBAGENT']._serialized_start = 5301
  _globals['_ACTIONINVOKESUBAGENT']._serialized_end = 5323
  _globals['_TOOLCONFIRMATIONREQUEST']._serialized_start = 5325
  _globals['_TOOLCONFIRMATIONREQUEST']._serialized_end = 5350
  _globals['_USERQUESTIONSREQUEST']._serialized_start = 5352
  _globals['_USERQUESTIONSREQUEST']._serialized_end = 5433
  _globals['_USERQUESTION']._serialized_start = 5435
  _globals['_USERQUESTION']._serialized_end = 5535
  _globals['_MULTIPLECHOICE']._serialized_start = 5537
  _globals['_MULTIPLECHOICE']._serialized_end = 5613
  _globals['_INPUTEVENT']._serialized_start = 5616
  _globals['_INPUTEVENT']._serialized_end = 5995
  _globals['_USERINPUT']._serialized_start = 5998
  _globals['_USERINPUT']._serialized_end = 6221
  _globals['_USERINPUT_MEDIA']._serialized_start = 6068
  _globals['_USERINPUT_MEDIA']._serialized_end = 6129
  _globals['_USERINPUT_PART']._serialized_start = 6131
  _globals['_USERINPUT_PART']._serialized_end = 6221
  _globals['_TOOLCONFIRMATION']._serialized_start = 6223
  _globals['_TOOLCONFIRMATION']._serialized_end = 6302
  _globals['_TRAJECTORYSTATEUPDATE']._serialized_start = 6305
  _globals['_TRAJECTORYSTATEUPDATE']._serialized_end = 6488
  _globals['_TRAJECTORYSTATEUPDATE_STATE']._serialized_start = 6423
  _globals['_TRAJECTORYSTATEUPDATE_STATE']._serialized_end = 6488
  _globals['_TOOLCALL']._serialized_start = 6490
  _globals['_TOOLCALL']._serialized_end = 6550
  _globals['_TOOLRESPONSE']._serialized_start = 6552
  _globals['_TOOLRESPONSE']._serialized_end = 6662
  _globals['_USERQUESTIONSRESPONSE']._serialized_start = 6665
  _globals['_USERQUESTIONSRESPONSE']._serialized_end = 6933
  _globals['_USERQUESTIONSRESPONSE_QUESTIONSRESPONSE']._serialized_start = 6841
  _globals['_USERQUESTIONSRESPONSE_QUESTIONSRESPONSE']._serialized_end = 6923
  _globals['_USERQUESTIONANSWER']._serialized_start = 6936
  _globals['_USERQUESTIONANSWER']._serialized_end = 7070
  _globals['_MULTIPLECHOICEANSWER']._serialized_start = 7072
  _globals['_MULTIPLECHOICEANSWER']._serialized_end = 7154
  _globals['_MEDIA']._serialized_start = 6068
  _globals['_MEDIA']._serialized_end = 6129
# @@protoc_insertion_point(module_scope)
